# Generated by Django 3.0.4 on 2020-09-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20200907_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='prac_secured_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='prac_total_mark',
            field=models.FloatField(default=0),
        ),
    ]
