# Generated by Django 3.0.4 on 2020-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='student_id',
            field=models.CharField(default=23334, max_length=6),
            preserve_default=False,
        ),
    ]
