# Generated by Django 3.0.4 on 2020-09-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_otp_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
