# Generated by Django 3.0.4 on 2020-09-11 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='top_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 10, 59, 29, 571532)),
        ),
    ]
