# Generated by Django 3.0.4 on 2020-09-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_auto_20200911_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='top_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
