# Generated by Django 3.0.4 on 2020-09-11 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_auto_20200911_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='top_create',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
